---
title: "Rmd + Shiny"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(ggplot2)
library(southafricastats)
```

```{r, include=FALSE}


totals <- population_zaf %>% 
  filter(year == 2013) %>% 
  select(province, total)

compare_provinces <- mortality_zaf %>%
    left_join(population_zaf) %>%
    filter(!is.na(total)) %>%
    mutate(mortality = deaths / total * 1e3) %>%
    group_by(province, indicator) %>%
    summarise(mortality = mean(mortality, na.rm = TRUE)) %>%
    ungroup %>%
    left_join(totals) %>%
    spread(indicator, mortality)

```



```{r, eval=FALSE, include=FALSE}
ggplot(compare_provinces, aes(`Cerebrovascular diseases (I60-I69)`,
                              `Diabetes mellitus (E10-E14)`,
                              size = total,
                              label = province)) +
    geom_point(alpha = 0.7, color = "midnightblue") +
    geom_text(aes(size = 1.8e6), vjust = -1.5) +
    theme_minimal() +
    xlim(c(0.3, 0.7)) + 
    ylim(c(0.3, 0.55)) +
    theme(legend.position="none")
```

```{r, echo=FALSE}
selectInput(inputId = "x",
            label = "X-axis:",
            choices = colnames(compare_provinces)[3:20],
            selected = "Other forms of heart disease (I30-I52)")

selectInput(inputId = "y",
            label = "Y-axis:",
            choices = colnames(compare_provinces)[3:20],
            selected = "Non-natural causes")
```



```{r, include=FALSE}

selected_df <- reactive({
    subset_df <- compare_provinces[, c(1:2,
                                     which(colnames(compare_provinces) == input$x),
                                     which(colnames(compare_provinces) == input$y))]
    colnames(subset_df) <- c("province", "total",
                             "selected_x", "selected_y")
    subset_df
})


```
```{r, echo=FALSE}

fillCol(height = 1800,
renderPlot({
    ggplot(selected_df(), aes(x = selected_x,
                              y = selected_y,
                              size = total,
                              label = province)) +
        geom_point(alpha = 0.7, color = "midnightblue") +
        theme_minimal() +
        labs(x = input$x, y = input$y) +
        geom_text(aes(size = 1e7), vjust = 2) +
        theme_minimal(base_size = 14) +
        theme(legend.position="none")
}),width = 1800)
```


